source 'https://github.com/CocoaPods/Specs.git'
workspace 'challenger.xcworkspace'
platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
pod "AutoKeyboardScrollView", :git => 'https://github.com/undrtone/AutoKeyboardScrollView.git', :branch => 'swift3'
pod 'UIColor_Hex_Swift'
pod 'Alamofire'
pod 'XCGLogger'
pod 'SVProgressHUD'
pod 'Starscream'
pod "EasyPeasy"
pod 'SwiftyUserDefaults'
pod 'ObjectMapper'
pod 'SWTableViewCell'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod "PKHUD"
pod 'AlamofireImage'
pod 'AlamofireObjectMapper'
pod 'Instabug'
pod "QRCode"
end

project 'admin/admin.xcodeproj'
project 'postgame/postgame.xcodeproj'

target :admin do
project 'admin/admin.xcodeproj'
shared_pods
end

target :postgame do
project 'postgame/postgame.xcodeproj'
shared_pods
end
