source 'https://github.com/CocoaPods/Specs.git'
workspace 'challenger.xcworkspace'
platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
pod "AutoKeyboardScrollView", '~> 1.4'
pod 'UIColor_Hex_Swift', '~> 2.1'
pod 'Alamofire', '~> 3.3'
pod 'XCGLogger', '~> 3.3'
pod 'SVProgressHUD'
pod 'Starscream', '~> 1.1.3'
pod "EasyPeasy"
pod 'SwiftyUserDefaults'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SWTableViewCell', '~> 0.3.7'
end

project 'admin/admin.xcodeproj'
project 'postgame/postgame.xcodeproj'

target :admin do
project 'admin/admin.xcodeproj'
shared_pods
end

target :postgame do
project 'postgame/postgame.xcodeproj'
shared_pods
end
