arenaWidth = 8 # 场地长
arenaHeight = 6 # 场地高
warmup = 2.0 # 预热时间
t1 = 2.0 # 按钮读条时间1
t2 = 2.2 # 按钮读条时间2
t3 = 2.5 # 按钮读条时间3
tRampage = 1.0 # 暴走读条时间
goldBonus = [ 1, 1 ] # 按钮金币奖励，赏金-生存
touchPunish = [ 30.0, 10.0 ] # 激光触碰惩罚，赏金-生存
mode2InitGold = [ 60, 90, 120, 150 ] # 生存初始金币， 1-4人
mode2GoldDropRate = [ 2, 3, 4, 5 ] # 生存金币下降速度, 1-4人
maxEnergy = 100.0 # 最大能量值
mode1TotalTime = 60.0 # 赏金模式总时长
laserSpeed = 0.25 # 激光亮起间隔(初始速度)
laserSpeedup = 0.05 # 激光每档亮起间隔减少值(加速度)
laserAppearTime = 3.0 # 激光预警时间
laserPauseTime = 10.0 # 激光碰人后硬直时间

energyBonus = [
[ 0.0, 0.0, 0.0, 0.0 ], # t0-t1能量奖励, 1人
[ 50.0, 40.0, 30.0, 20.0 ], # t1-t2能量奖励, 2人
[ 40.0, 32.0, 24.0, 16.0 ], # t2-t3能量奖励, 3人
[ 30.0, 24.0, 18.0, 12.0 ] # t3能量奖励, 4人
]

initButtonNum = [ 20, 30, 40, 50 ] # 初始按钮个数, 1-4人
buttonHideTime = [ 6.0, 6.0 ] # 按钮触碰后新按钮出现间隔, 赏金-生存
rampageTime = [ 20.0, 20.0 ] # 暴走持续时间, 赏金-生存
firstComboInterval = [ 5.0, 4.0, 3.0, 2.0 ] # 第一次连击时间间隔, 1-4人
comboInterval = [ 3.0, 3.0, 2.0, 2.0 ] # 第n次连击时间间隔, n>1, 1-4人
firstComboExtra = 30.0 # 第一次连击额外能量
comboExtra = 15.0 # 第n次连击额外能量, n>1
invincibleTime = 3.0 # 玩家触碰激光后的无敌时间
mode1TouchPunish = 0.3 # 赏金模式触碰激光金币惩罚, 单位百分比
mode2TouchPunish = 10 # 生存模式触碰激光金币惩罚, 单位个数
mode2GoldDropInterval = 1.0 # 生存模式每隔几秒金币减少1


# render configures, 显示相关，仅与模拟器有关参数
arenaCellSize = 140 # 格子大小
arenaBorder = 24 # 格子边框大小
playerSize = 50.0 # 玩家大小
webScale = 0.5 # 模拟器显示缩放比例
buttonWidth = 60.0 # 按钮宽度
buttonHeight = 30.0 # 按钮高度
playerSpeed = 200.0 # 玩家移动速度
#墙壁信息

walls = [
[ 4, 0, 5, 0 ],
[ 1, 0, 1, 1 ],
[ 6, 0, 6, 1 ],
[ 0, 1, 1, 1 ],
[ 2, 1, 3, 1 ],
[ 3, 1, 4, 1 ],
[ 6, 1, 7, 1 ],
[ 2, 1, 2, 2 ],
[ 5, 1, 5, 2 ],
[ 2, 2, 3, 2 ],
[ 3, 2, 4, 2 ],
[ 4, 2, 5, 2 ],
[ 1, 2, 1, 3 ],
[ 6, 2, 6, 3 ],
[ 0, 3, 1, 3 ],
[ 2, 3, 3, 3 ],
[ 4, 3, 5, 3 ],
[ 6, 3, 7, 3 ],
[ 2, 3, 2, 4 ],
[ 3, 3, 3, 4 ],
[ 0, 4, 1, 4 ],
[ 1, 4, 2, 4 ],
[ 4, 4, 5, 4 ],
[ 5, 4, 6, 4 ],
[ 6, 4, 7, 4 ],
[ 4, 4, 4, 5 ],
[ 2, 5, 3, 5 ],
[ 5, 5, 6, 5 ]
]

# 入口坐标
[arenaEntrance]
x = 0
y = 4

# 出口坐标
[arenaExit]
x = 6
y = 0
