// Code generated by "stringer -type=SocketGroupType"; DO NOT EDIT

package core

import "fmt"

const (
	_SocketGroupType_name_0 = "SG_Game"
	_SocketGroupType_name_1 = "SG_Api"
	_SocketGroupType_name_2 = "SG_Client"
	_SocketGroupType_name_3 = "SG_Admin"
)

var (
	_SocketGroupType_index_0 = [...]uint8{0, 7}
	_SocketGroupType_index_1 = [...]uint8{0, 6}
	_SocketGroupType_index_2 = [...]uint8{0, 9}
	_SocketGroupType_index_3 = [...]uint8{0, 8}
)

func (i SocketGroupType) String() string {
	switch {
	case i == 0:
		return _SocketGroupType_name_0
	case i == 2:
		return _SocketGroupType_name_1
	case i == 8:
		return _SocketGroupType_name_2
	case i == 24:
		return _SocketGroupType_name_3
	default:
		return fmt.Sprintf("SocketGroupType(%d)", i)
	}
}
